package com.example.housing;

import java.util.Iterator;
import java.util.List;
import com.example.housing.data.model.Offer;
import com.example.housing.data.model.Photo;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;

public class Fotos extends CustomComponent {
	private static final long serialVersionUID = 1L;

	private VerticalLayout mainLayout;

	public Fotos(final Offer o, final AngebotErstellen angebotErstellen) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		Label title = new Label("Bilder zu diesem Angebot bearbeiten");
		title.addStyleName("title");
		mainLayout.addComponent(title);
		
		//Bilder
		Label bilder = new Label("Bilder hinzufügen");
		bilder.addStyleName("AbschnittLabel");

		Upload bilderup = new Upload("Fotos hochladen (max. 5 Fotos pro Angebot):", angebotErstellen);
		bilderup.setImmediate(true);
		bilderup.addSucceededListener(angebotErstellen);
				
		mainLayout.addComponent(bilder);
		mainLayout.addComponent(bilderup);
		mainLayout.addComponent(new Label());		
		
		//Bilder Löschen
		Label bilderLoeschen = new Label("Aktuelle Bilder");
		bilderLoeschen.addStyleName("AbschnittLabel");
		
		try{
			mainLayout.addComponent(bilderLoeschen);
			List<Photo> photo = o.getPhotos();
			Iterator<Photo> it = photo.iterator();
			if(!it.hasNext()){
				mainLayout.addComponent(new Label("Es wurden noch keine Bilder zu diesem Angebot hochgeladen."));
			}else{
				while(it.hasNext()){
					Fotozeile f = new Fotozeile(it.next(), o);
					mainLayout.addComponent(f);
				}
			}
			mainLayout.addComponent(new Label());	
		}catch(Exception e){
			mainLayout.addComponent(new Label("Es wurden noch keine Bilder zu diesem Angebot hochgeladen."));
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);
		return mainLayout;
	}
}
