package com.example.housing;

import java.io.ByteArrayInputStream;
import java.io.InputStream;

import com.example.housing.data.model.Offer;
import com.example.housing.data.model.Photo;
import com.example.housing.data.provider.OfferProvider;
import com.example.housing.data.provider.PhotoProvider;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.StreamResource;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;

public class Fotozeile extends CustomComponent {
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;

	public Fotozeile(final Photo photo, final Offer offer) {
		//Layout
		buildMainLayout();
		setCompositionRoot(mainLayout);
		HorizontalLayout ergebnisLayout = new HorizontalLayout();
		ergebnisLayout.setMargin(true);
		ergebnisLayout.setHeight("100px");

		//Bild
		StreamResource resource = new StreamResource(
				new StreamResource.StreamSource() {
					private static final long serialVersionUID = 1L;

					@Override
					public InputStream getStream() {
						InputStream bais = new ByteArrayInputStream(
								photo.getPicture());
						return bais;
					}
				}, "Bild_1");
		resource.setCacheTime(0);

		Image image = new Image(null, resource);
		image.setHeight("80px");
		image.setWidth("80px");
		image.markAsDirty();
		ergebnisLayout.addComponent(image);

		//Loeschen Button
		Button loeschenButton = new Button("Dieses Bild löschen");
		ergebnisLayout.addComponent(loeschenButton);

		loeschenButton.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			public void buttonClick(ClickEvent event) {
				PhotoProvider pp = new PhotoProvider();
				pp.removePhoto(photo);

				int id = offer.getIdOffer();//Angebot muss neu aus der DB geladen werden
				OfferProvider offerProvider = new OfferProvider();
				Offer newOffer = offerProvider.find(id);
				String name = "AngebotErstellen";
				getUI().getNavigator().addView(name,
						new AngebotErstellen(newOffer));
				getUI().getNavigator().navigateTo(name);
			}
		});
		mainLayout.addComponent(ergebnisLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);
		return mainLayout;
	}
}