package com.example.housing;

import java.util.List;

import com.example.housing.data.model.Offer;
import com.example.housing.data.model.User;
import com.example.housing.data.provider.OfferProvider;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class UserAngebote extends CustomComponent {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VerticalLayout mainLayout;
	private User user;

	public UserAngebote(User u) {
		
		this.user = u;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		List<Offer> offers = new OfferProvider().findByUser(user);
		
		if(offers.isEmpty()) {
			
			Label ergebnisString = new Label("Der User hat bisher keine Wohnungsangebote erstellt.");
			ergebnisString.addStyleName("AbschnittLabel");
			mainLayout.addComponent(ergebnisString);
			
		} else {
			
			Label ergebnisString = new Label("Wohnungsangebote des Users");
			ergebnisString.addStyleName("AbschnittLabel");
			mainLayout.addComponent(ergebnisString);
			
			for(Offer o : offers) {
				mainLayout.addComponent(new Listenzeile(o));
			}
			
		}
		
	}
	
	/**
	 * Builds the main layout.
	 *
	 * @return the vertical layout
	 */
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);

		mainLayout.setMargin(false);

		return mainLayout;

	}

}
