package com.example.housing;

import com.example.housing.data.model.User;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.LayoutEvents.LayoutClickEvent;
import com.vaadin.event.LayoutEvents.LayoutClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class UserZeile extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/** The main layout. */
	@AutoGenerated
	private VerticalLayout mainLayout;
	
	public UserZeile(final User u) {
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		GridLayout ergebnisLayout = new GridLayout(3, 1);
		ergebnisLayout.setMargin(false);
		ergebnisLayout.addStyleName("Listenzeile");
		ergebnisLayout.setSizeFull();
		ergebnisLayout.setHeight("50px");
		
		Label userID = new Label("ID: " + u.getIdUser());
		ergebnisLayout.addComponent(userID, 0, 0);
		
		Label userMail = new Label("E-Mail-Adresse: " + u.getEmail());
		ergebnisLayout.addComponent(userMail, 1, 0);
		
		String level;
		switch(u.getAccessLevel()) {
			case 1:
				level = "DH-Studentin / DH-Student";
				break;
			case 2:
				level = "Administrator";
				break;
			default:
				level = "Normaler User";
		}
		
		Label userLevel = new Label("Zugangslevel: " + level);
		ergebnisLayout.addComponent(userLevel, 2, 0);
		
		ergebnisLayout.addLayoutClickListener(new LayoutClickListener() {
			
			@Override
			public void layoutClick(LayoutClickEvent event) {
				
				String name = "UserProfil";
				getUI().getNavigator().addView(name, new UserProfil(u));
				getUI().getNavigator().navigateTo(name);
				
			}
		});
		
		mainLayout.addComponent(ergebnisLayout);
	
	}
	
	/**
	 * Builds the main layout.
	 *
	 * @return the vertical layout
	 */
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);

		mainLayout.setMargin(false);

		return mainLayout;

	}

}
